// Assembles the Pop skin into dist/pop.css using cascade layers:
//   nl.tokens < nl.base < nl.components < nl.utilities < (consumer's unlayered CSS)
// Any unlayered rule in the consuming app wins over the library, whatever its specificity.
import fs from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const manifest = JSON.parse(fs.readFileSync('src/manifest.json', 'utf8'));
const read = (p) => fs.readFileSync(`src/${p}`, 'utf8').trim();
const tokens = fs.readFileSync(require.resolve('@nerdlab/tokens/pop.css'), 'utf8').replace(/^\/\*\*[\s\S]*?\*\/\s*/, '').trim();
const indent = (s) => s.split('\n').map((l) => (l ? `  ${l}` : l)).join('\n');
const layer = (name, files) => `@layer nl.${name} {\n${indent(files.map(read).join('\n\n'))}\n}`;

const out = [
  '/* @nerdlab/css-pop — generated by scripts/build.mjs, do not edit. Fonts: @nerdlab/css-pop/fonts.css */',
  '@layer nl.tokens, nl.base, nl.components, nl.utilities;',
  `@layer nl.tokens {\n${indent(tokens)}\n}`,
  layer('base', manifest.base),
  layer('components', manifest.components),
  layer('utilities', manifest.utilities),
].join('\n\n') + '\n';

fs.mkdirSync('dist', { recursive: true });
fs.writeFileSync('dist/pop.css', out);
fs.copyFileSync('src/fonts.css', 'dist/fonts.css');

// Every source file must be listed exactly once: an unlisted file would silently vanish from the build.
const listed = [...manifest.base, ...manifest.components, ...manifest.utilities];
const onDisk = fs.readdirSync('src', { recursive: true }).filter((f) => f.endsWith('.css') && f !== 'fonts.css');
const missing = onDisk.filter((f) => !listed.includes(f));
if (missing.length || new Set(listed).size !== listed.length) throw new Error(`manifest mismatch: ${missing.join(', ') || 'duplicate entry'}`);
console.log(`css-pop: ${listed.length} files → dist/pop.css (${(out.length / 1024).toFixed(1)} KB)`);
